<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpezakn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpezakn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWpezakn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWpezakn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWpezakn\appProdProjectContainer([
    'container.build_hash' => 'Wpezakn',
    'container.build_id' => 'a449c03b',
    'container.build_time' => 1605827378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpezakn');
